In [4]:

#import necessary libraries
import pandas as pd

In [6]:
#Load the datasets and print first five rows
df=pd.read_csv("C:/Users/kartik/Downloads/archive (9)/spam.csv",encoding='latin1')
df.drop(['Unnamed: 2'],axis=1,inplace=True)
df.drop(['Unnamed: 3'],axis=1,inplace=True)
df.drop(['Unnamed: 4'],axis=1,inplace=True)

df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
df.groupby('v1').describe()

v2                                                               
     count unique                                                top freq
v1                                                                       
ham   4825   4516                             Sorry, I'll call later   30
spam   747    653  Please call our customer service representativ...    4

**Observation:**
Group the dataset based on two categories ham and spam

**b) Create a seperate column names spam and assign numerical values using lamba function.**

In [8]:
df['spam']=df['v1'].apply(lambda x:1 if x=='spam' else 0)
df.head()

v1                                                 v2  spam
0   ham  Go until jurong point, crazy.. Available only ...     0
1   ham                      Ok lar... Joking wif u oni...     0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3   ham  U dun say so early hor... U c already then say...     0
4   ham  Nah I don't think he goes to usf, he lives aro...     0

**Observation:**
A lambda function is used to map 0 for ham messages and 1 for spam messages so as to make computation easier.

**c) Split the dataset for traing and testing the model.**

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.v2,df.spam)

**d) Import CountVectorizer to create the matrix.**

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
x_train_count=v.fit_transform(x_train.values)
x_train_count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

**Observation:**
importing count vectorizer from sklearn library so to convert the given dataset into vector form

**e) Import MultinomialNB and fit the dataset.**

In [11]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(x_train_count,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

**Observation:**
Importing MultinomialNB model from sklearn and fit the dataset

In [12]:
emails=['Hey mohan,can we get together to watch footbal game tomorrow?',
       'Upto 20% discount on parking,exclusive offer just for ypu,Dont miss']
emails_count=v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

**f) Calculation of  the accuracy score.**

In [13]:
# evaluating the model
x_test_count=v.transform(x_test)
model.score(x_test_count,y_test)

0.9777458722182341

In [14]:
from sklearn.pipeline import Pipeline
clf=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

**Observation:**
Pipeline is used to ensemble several steps that can be cross validated together while setting different parameters.

In [15]:
clf.fit(x_train,y_train)

Pipeline(memory=None,
         steps=[('vectorizer',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('nb',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [16]:
clf.score(x_test,y_test)

0.9777458722182341

In [17]:
clf.predict(emails)

array([0, 1], dtype=int64)

**Observation:**
According to model prediction the first message is not a spam where as second message is a spam message